In [80]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import sklearn 

In [81]:
breastcancer= pd.read_csv('D:/Top Mentor/ml/22 july/breast-cancer.csv')

In [82]:
breastcancer.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [83]:
#now we check the shape of data
breastcancer.shape

(569, 33)

In [84]:
#we have 569 rows and 33 columns

In [123]:

#now we fing some info

In [85]:
breastcancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [86]:
#now we check is there any null values

In [87]:
breastcancer.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [88]:
#according to that a column name unnamed:32 have 569 (all rows) are empty, so we need to remove it.
#and we also remove id column

In [89]:
#before revoming copy our data into other variable, so our original data did not change

In [90]:
breastcancer1=breastcancer.copy()


In [91]:

breastcancer1= breastcancer1.drop(['Unnamed: 32','id'],axis=1)


In [92]:
breastcancer1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [93]:
#In our datat there is one categorical column named diagnosis, now we changed it into numerical 

In [94]:
breastcancer1['diagnosis'].unique()       #here we check which value present in diagnosis with the help of unique 

array(['M', 'B'], dtype=object)

In [95]:
breastcancer1['diagnosis']=breastcancer1['diagnosis'].map({"M":1,"B":0}).astype(int)   #coverting into numerical

In [96]:
breastcancer1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [97]:
#split it into x and y

In [98]:
x=breastcancer1.iloc[:,1:]    #independent
y=breastcancer1.iloc[:,0]      #dependent

In [99]:
x.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [100]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: diagnosis, dtype: int32

# KNN Model

In [101]:
# importing algorithm
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score


import warnings
warnings.filterwarnings('ignore')    #ignore warnings

### Do train test split


In [102]:
X_train,X_test,y_train,y_test= train_test_split(x, y, test_size=0.2, random_state=42)

In [103]:
len(X_train), len(y_train)

(455, 455)

In [104]:
len(X_test), len(y_test)

(114, 114)

In [105]:
kn= KNeighborsClassifier(n_neighbors=5)  # saving in variable 
#our default k value is 5
#now we train the model

### Train the model

In [106]:
kn.fit(X_train,y_train)           #give the data to knn

KNeighborsClassifier()

### Do the predictions

In [107]:
y_train_pred = kn.predict(X_train)

### Check train model accuracy

In [108]:
print(f'The training accuracy for k:5 = {accuracy_score(y_train,y_train_pred)}')

The training accuracy for k:5 = 0.9406593406593406


In [109]:
kn.score(X_train,y_train)  # single line accuracy 

0.9406593406593406

# confusion matrix:


In [110]:
from sklearn.metrics import confusion_matrix

In [111]:
confusion_matrix(y_train,y_train_pred)

array([[281,   5],
       [ 22, 147]], dtype=int64)

# classification_report

In [112]:
from sklearn.metrics import classification_report


In [113]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95       286
           1       0.97      0.87      0.92       169

    accuracy                           0.94       455
   macro avg       0.95      0.93      0.94       455
weighted avg       0.94      0.94      0.94       455



# Now train test data and predict value

In [114]:
y_test_pred = kn.predict(X_test)

In [115]:
print(f'accuracy for test data with k:5 = {accuracy_score(y_test,y_test_pred)}')

accuracy for test data with k:5 = 0.956140350877193


In [116]:
print(confusion_matrix(y_test,y_test_pred))

[[71  0]
 [ 5 38]]


In [117]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        71
           1       1.00      0.88      0.94        43

    accuracy                           0.96       114
   macro avg       0.97      0.94      0.95       114
weighted avg       0.96      0.96      0.96       114



# how to find the best k _value for the data :

so there is a change for any odd value to be the best : so we can select some range and check there

In [118]:
k_value= np.arange(3,51,2)       #create a array for k values
print(k_value)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [119]:
train_accuracy = np.empty(len(k_value))  # 24 empty values we are making 
test_accuracy = np.empty(len(k_value))   # 24 empty values we are making 


In [120]:
train_accuracy

array([-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ,  0.5 , -0.25,  0.25,
        0.  ,  0.5 ,  0.25,  0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ,
       -0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25])

In [121]:
#its a default empty value we can change it 

In [122]:
# loop to each value and train the KNN 

for i , j in enumerate(k_value): # i is for index and j is for to collect value 
    
    reg = KNeighborsClassifier(n_neighbors=j) # j will update for every iteration
    
    # fit the data to KNN 
    reg.fit(X_train,y_train) # training completed 
    
    # find the training accuracy and save using score [singe line]
    train_accuracy[i] = reg.score(X_train,y_train) # here I will get training accuracy for current j value 
    test_accuracy[i] = reg.score(X_test,y_test)  # single lines for current j value 
    
    # print each accuracy value for current k:
    print(f'train Accuracy score when k : {j} = {train_accuracy[i]} , Test accuracy when k :{j} = {test_accuracy[i]}')
    

train Accuracy score when k : 3 = 0.9494505494505494 , Test accuracy when k :3 = 0.9298245614035088
train Accuracy score when k : 5 = 0.9406593406593406 , Test accuracy when k :5 = 0.956140350877193
train Accuracy score when k : 7 = 0.9406593406593406 , Test accuracy when k :7 = 0.956140350877193
train Accuracy score when k : 9 = 0.9318681318681319 , Test accuracy when k :9 = 0.956140350877193
train Accuracy score when k : 11 = 0.9318681318681319 , Test accuracy when k :11 = 0.9824561403508771
train Accuracy score when k : 13 = 0.9296703296703297 , Test accuracy when k :13 = 0.9736842105263158
train Accuracy score when k : 15 = 0.9230769230769231 , Test accuracy when k :15 = 0.9649122807017544
train Accuracy score when k : 17 = 0.9230769230769231 , Test accuracy when k :17 = 0.9649122807017544
train Accuracy score when k : 19 = 0.9208791208791208 , Test accuracy when k :19 = 0.9649122807017544
train Accuracy score when k : 21 = 0.9186813186813186 , Test accuracy when k :21 = 0.96491228

In [124]:
train_accuracy

array([0.94945055, 0.94065934, 0.94065934, 0.93186813, 0.93186813,
       0.92967033, 0.92307692, 0.92307692, 0.92087912, 0.91868132,
       0.91648352, 0.91868132, 0.91648352, 0.91648352, 0.91868132,
       0.91648352, 0.91428571, 0.91428571, 0.91648352, 0.91648352,
       0.91868132, 0.91428571, 0.91428571, 0.90989011])

In [125]:
test_accuracy

array([0.92982456, 0.95614035, 0.95614035, 0.95614035, 0.98245614,
       0.97368421, 0.96491228, 0.96491228, 0.96491228, 0.96491228,
       0.95614035, 0.94736842, 0.94736842, 0.94736842, 0.94736842,
       0.94736842, 0.94736842, 0.94736842, 0.94736842, 0.94736842,
       0.94736842, 0.94736842, 0.94736842, 0.94736842])

In [126]:
# so in test_accuracy variable we have each k value accuray so find the best means max from it 
# and checks it k-value 
print(max(test_accuracy))


0.9824561403508771


In [127]:
a = np.where(test_accuracy == max(test_accuracy))
a

(array([4], dtype=int64),)

In [128]:
#find its index

In [130]:
k_value[a]

array([11])

In [131]:
#k=11 is best fit value for our model

# Now train the model with k = 11

In [132]:
# know develop the KNN model:

from sklearn.neighbors import KNeighborsClassifier # importing algorithm 
reg = KNeighborsClassifier(n_neighbors=11)  # saving in variable 

# default k value is 5 
# we are gonig to train the data with k = 11 [first we will see the result with default k value]
# then we can select the best k_value which required 

reg.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [135]:
y_train_pred1 = reg.predict(X_train)

In [136]:
from sklearn.metrics import accuracy_score

In [139]:
print(f'The training accuracy for k:11 = {accuracy_score(y_train,y_train_pred1)}')

The training accuracy for k:11 = 0.9318681318681319


In [140]:
reg.score(X_train,y_train)  # single line accuracy 

0.9318681318681319

In [141]:
# confusion matrix:

from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,y_train_pred)

array([[281,   5],
       [ 22, 147]], dtype=int64)

In [142]:
from sklearn.metrics import classification_report

print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95       286
           1       0.97      0.87      0.92       169

    accuracy                           0.94       455
   macro avg       0.95      0.93      0.94       455
weighted avg       0.94      0.94      0.94       455



In [143]:
#for test data

In [144]:
# when k =11 these are our test data results 
y_test_pred2 = reg.predict(X_test)


In [145]:
print(f'accuracy for test with k:11 = {accuracy_score(y_test,y_test_pred2)}')


accuracy for test with k:11 = 0.9824561403508771


In [147]:
print(confusion_matrix(y_test,y_test_pred))

[[71  0]
 [ 5 38]]


In [ ]:
print(confusion_matrix(y_test,y_test_pred))